project:
  type: book
  output-dir: docs

book:
  title: "Transcriptome Data Analysis in Non-model Organisms"
  author: 
    - "Jiratchaya Nuanpirom"
    - "Prasert Yodsawat"
    - "Ponsit Sathapondecha"
  date: today
  chapters:
    - index.qmd
    - 01_intro_mobaxterm.qmd
    - 02_basic_bash.qmd
    - 03_sra.qmd
    - 04_qc.qmd
    - 05_denovo_assembly.qmd
    - 06_de_analysis.qmd
    - 07_annotation.qmd
    - references.qmd
  repo-url: https://github.com/JirathNuan/rnaseq-nonmodel
  repo-actions: [edit]
  downloads: [pdf]


bibliography: references.bib

format:
  html:
    theme: minimal
    fontsize: 1em
  pdf:
    documentclass: article
    pdf-engine: wkhtmltopdf
    papersize: A4
    number-sections: false


editor: visual

