project:
  type: book

book:
  title: "Transcriptome Data Analysis in Non-model Organisms"
  author: 
    - "Ponsit Sathapondecha"
    - "Jiratchaya Nuanpirom"
    - "Prasert Yodsawat"
  date: today
  chapters:
    - index.qmd
    - 01_intro_mobaxterm.qmd
    - 02_basic_bash.qmd
    - 03_sra.qmd
    - 04_qc.qmd
    - 05_denovo_assembly.qmd
    - 06_de_analysis.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: zephyr
  pdf:
    documentclass: scrreprt

editor: visual

